# 配置文件

DAILY_TIME: "8:30" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2022-12-16" # 纪念日
CITY: "武汉"

BIRTHDAY:
  - "10-17"
  - "11-27"

APP_ID: "wx1f013e616c2841d2"
APP_SECRET: "abbf3457f795d9a9cf4e9e373bfafb3e"

USER_ID: 
  - "o3ZGO5yK4c4y-TOP3PnkIXeZ5dyc"
  - "o3ZGO5yK4c4y-TOP3PnkIXeZ5dyc" # 你可以通过配置多个USER_ID来设置多个接受者，如果接受者只有一人删除本行即可
TEMPLATE_ID: "nDyRLyRrPgSQZg7YwYooPJvsREezJZzVFCT9p4xyJNI"
